### ISSUE TITLE
Is "Reapply Wounds Based on Current HP" working as intended in Cyberpunk-Red?

### ISSUE THREAD

**Issue by DigitalChicanaery** [shemetz/tokenmagic-automatic-wounds#10]
Is "Reapply Wounds Based on Current HP" working as intended in Cyberpunk-Red? The macro seems to paint _all_ tokens with blood, even if they have zero HP loss.

**Comment by billytherex** [comment]
I added a pull request that corrects the issue.

**Comment by shemetz** [comment]
Fixed in v1.0.8, thank you @billytherex!
