### ISSUE TITLE
[Compability] Please add the Warhammer system to it

### ISSUE THREAD

**Issue by danil0man** [shemetz/tokenmagic-automatic-wounds#11]
As the title say. Please could you add this to the warhammer fantasy 4th system?

**Comment by shemetz** [comment]
Sure.  @danil0man can you tell me which field in that system represents health/wounds, and if it goes up or down?

**Comment by danil0man** [comment]
This are the fields you may need  
current HP: data.status.wounds.value
Max HP: data.status.wounds.max
It goes down. so the more damage you take the less hp you have. Hit me up if you need something else and thx you so much

**Comment by shemetz** [comment]
Ummmm, wait, I think I already added compatibility for this!

This is "Warhammer Fantasy Roleplay 4e (wfrp4e)", right?  it should already be working, as mentioned in the readme.

@danil0man try it!
