### ISSUE TITLE
[Feature Request] Disable Module in Settings

### ISSUE THREAD

**Issue by MrVauxs** [shemetz/tokenmagic-automatic-wounds#12]
A quick "disable the modules functionality" setting would be nice to have for other modules to temporarily turn on and off when say, summoning tokens and in turn, "hurting" them by changing their HP, causing them to get a blood splatter when they honestly shouldn't.

**Comment by shemetz** [comment]
there's a built in macro for that!  see https://github.com/shemetz/tokenmagic-automatic-wounds#macros-in-tokenmagic-automatic-wounds-compendium-pack

you want "Toggle Auto-Wounds For Token" or "Toggle Auto-Wounds For Actor", to disable it for certain bloodless enemies.

**Comment by shemetz** [comment]
FYI, if you're developing a module that wants to interact like this, you can use:

```
const MODULE_ID = 'tokenmagic-automatic-wounds'
const FLAG_DISABLE_WOUNDS = 'enabled-for-token'
actor.setFlag(MODULE_ID, FLAG_DISABLE_WOUNDS, false)
```

**Comment by MrVauxs** [comment]
Is there a flag stored when this is done so I can re-enable the feature?

wt., 20 gru 2022, 09:45 użytkownik shemetz ***@***.***>
napisał:

**Comment by MrVauxs** [comment]
That doesn't help with anything because the wounds don't disappear on setting the flag.

**Comment by MrVauxs** [comment]
In the end I found I can just use `TokenMagicAutomaticWounds.toggleDisableWounds`, that will suffice.
