### ISSUE TITLE
PbtA Wounds please!

### ISSUE THREAD

**Issue by steve-ela** [shemetz/tokenmagic-automatic-wounds#20]
THe macro does not work with PbtA style wound track. Would love to add this to my Monster of the Week game

**Comment by shemetz** [comment]
Added in v1.1.3

**Comment by shemetz** [comment]
**However**, this is currently bugged, due to a PBTA system bug:  see https://gitlab.com/asacolips-projects/foundry-mods/pbta/-/issues/87

Until that system's code is updated to fix that bug, this module will actually not function properly for PBTA systems.  (it should be a quick fix though)
