### ISSUE TITLE
How to use it with the OSE system

### ISSUE THREAD

**Issue by Mad7eo** [shemetz/tokenmagic-automatic-wounds#21]
Hi, is there a way to configure it to function with Old School Essentials? https://github.com/vttred/ose/

**Comment by shemetz** [comment]
sure, from a glance it looks like it uses `system.hp.value` and `system.hp.max` like most other systems.

**Comment by shemetz** [comment]
Added in v1.1.4

**Comment by Mad7eo** [comment]
It doesn't work right now, I'm on Foundry 11.314 - OSE 1.9.3 (latest) and tokenmagic-automatic-wounds 1.1.4.
Works fine in my dnd5e world

**Comment by shemetz** [comment]
oops, used `ose-dev` instead of `ose`, their system json confused me.  fixed in v1.1.5
