### ISSUE TITLE
Not working in swade

### ISSUE THREAD

**Issue by ddbrown30** [shemetz/tokenmagic-automatic-wounds#22]
I'm not sure if I'm just missing something but the module doesn't seem to do anything for me. I'm using swade. I've tried and PCs and NPCs. I've tried setting the wounds manually on the sheet and tried applying wounds through both the default system interface and the Better Rolls 2 for SWADE module. Nothing seems to work. I also tried the reapply wounds macro and that does nothing either.

Manually apply the wound effect using the macro from Token FX works fine, so it's not an issue of something there not working.

I'm on Foundry 11.315, swade version 3.2.5, Token FX version 0.6.5.0, and your module version 1.1.7.

**Comment by peterprokurist** [comment]
It's the same for me.
Foundry v11.315
Savage Worlds Adventure Edition (SWADE) v3.3.11
Token Magic FX v0.6.5.0
Automatic Wounds v1.1.7

**Comment by shemetz** [comment]
Fixed in v1.1.8 probably (haven't tested it, but I saw a clear bug in the code).  Let me know if it does or doesn't work!

**Comment by ddbrown30** [comment]
It does seem to be fixed, thanks. FYI, because you've the new version as 12+ in the package interface (but not in the module.json) it doesn't automatically update for v11 even though it is compatible. I'd recommend updating the release info to have the min version be v11.

**Comment by shemetz** [comment]
Ah, that's because I wasn't sure if `foundry.utils.getProperty` exists in v11, and didn't want to risk it for such a small fix.  Are you sure it worked fine in v11?  if so I'll change it

**Comment by ddbrown30** [comment]
Yeah, it definitely works. I'm a mod dev too. All they did was remove support for directly calling getProperty and now require it be called through foundry.utils but it was possible to call it through foundry.utils in v11.

**Comment by shemetz** [comment]
they didn't remove support for it though - it only gives a deprecation warning!

but thanks, I'll update this now :)
