### ISSUE TITLE
Cannot be enabled due to issues in required dependencies

### ISSUE THREAD

**Issue by dolonite** [shemetz/tokenmagic-automatic-wounds#23]
Hello I am running a Star Wars 5E game which is based on the DND5E ruleset foundry version 12.327 and I cannot enable Token Magic - Automatic Wounds. When I hover my mouse over it I get the message "Cannot be enabled due to issues in required dependencies".

**Comment by shemetz** [comment]
I'm pretty sure this doesn't happen anymore - but just in case, try it in module version 1.1.8 (make sure to update TokenMagic if you can).
