### ISSUE TITLE
[Feature suggestion] pf2e - option to track wounded level 

### ISSUE THREAD

**Issue by MothMariner** [shemetz/tokenmagic-automatic-wounds#4]
Entirely wishlisting here, but could there be an options (for pf2e) to have it track levels of wounded rather than level of hp? Could be cool.

Thanks for reading!

**Comment by shemetz** [comment]
Sorry, this is a cool idea but it's too difficult to listen in the code for changes in the Wounded condition of an actor - plus, the condition is already making the wounded fact very visible.
