### ISSUE TITLE
Foundry Version 10 

### ISSUE THREAD

**Issue by HShuya** [shemetz/tokenmagic-automatic-wounds#7]
Hello, I was just wondering if you are planning to make this compatible with foundry Version 10.
Right now I get this error message
[tokenmagic-automatic-wounds] Metadata validation failed for module "tokenmagic-automatic-wounds": The file "scripts/tokenmagic-automatic-wounds.js" included by module tokenmagic-automatic-wounds does not exist
when trying to install the module. I dont know if that is coming from Version 10 or is a problem in 9 as well.

I really like this module and it would be nice if I could continue using it.
Thanks for your work.

Best Regards

**Comment by shemetz** [comment]
~~I wish I could, but TokenMagic still hasn't --~~

Oh sweet, [they did it 2 days ago!](https://github.com/Feu-Secret/Tokenmagic/issues/203)

I'll get right on updating this, thank you!

**Comment by kiloforce** [comment]
V10.285

![image](https://user-images.githubusercontent.com/433058/190534599-6cb61309-c972-425b-9f5f-358db9c55c1b.png)

**Comment by shemetz** [comment]
Fixed in v1.0.5
